version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bluemoon
    volumes:
      - ./src/db-core/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

  adminer:
    image: adminer
    restart: always
    ports:
        - 81:8080

  web:
    image: bluemoon
    ports: 
      - 80:8080
    depends_on:
      - db
    command: ["./wait-for-postgress.sh", "postgres:5432", "--", "npm", "run", "start"]