version: "3"
services:
  postgres:
    image: postgres
    restart: always
    expose:
      - 5432
  web:
    # replace username/repo:tag with your name and image details
    image: bluemoon
    build: .
    ports:
      - 80:8080
    depends_on:
      - postgres
    command: ["./wait-for-postgress.sh", "postgres:5432", "--", "npm", "run", "start:dev"]
  adminer:
    image: adminer
    restart: always
    expose:
      - 8081
    ports:
      - 81:8081
  visualizer:
    image: dockersamples/visualizer:stable
    expose:
      - 8082
    ports:
      - 82:8082
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"